name: example
description: Examples for cssinline
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  cssinline:
    path: ..

dev_dependencies:
  lints: ^2.0.0
