name: cssinline
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/fabricio-godoi/cssinline

environment:
  sdk: ^2.12.0

# Add regular dependencies here.
dependencies:
  csslib: ^1.0.0
  html: ^0.15.4
  path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  args: ^2.5.0
  io: ^1.0.4
  coverage: ^1.8.0
  logger: ^2.3.0
